
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin 2 as an output.
  pinMode(0, OUTPUT);
  pinMode(1, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(A0, OUTPUT);
  pinMode(A1, OUTPUT);
  pinMode(A2, OUTPUT);
  pinMode(A3, OUTPUT);
  pinMode(A4, OUTPUT);
  pinMode(A5, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(0, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, HIGH);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, HIGH);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
  digitalWrite(0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(1, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(5, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(6, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(7, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(8, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(9, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(10, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(11, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(12, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(13, LOW);  // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A0, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A1, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A2, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(A3, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A4, LOW);   // turn the LED OFF (HIGH is the voltage level)
  digitalWrite(A5, HIGH);   // turn the LED OFF (HIGH is the voltage level)
  delay(500);
}
